import Head from 'next/head'
import Navbar from '../components/Navbar';
import Card from '../components/Card';

export default function Home(props) {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />

                <body className="light" />
            </Head>
            <Navbar />  
            <div className="container-fluid content-inner pb-0">
                <div className="row">
                    {props.media.map((media) =>
                        <Card key={media.id} id={media.id} title={media.title} image={media.image} logo={media.logo} />
                    )}
                </div>
            </div>
        </div>
    )
}

export async function getServerSideProps() {
    // Fetch data from external API
    let media = [
        {
            id: 1,
            title: "Westworld",
            image: "https://www.themoviedb.org/t/p/original/t80UpnIq8452GOg2I6U4Zbm84b7.jpg",
            logo: "https://www.themoviedb.org/t/p/original/418NJcFFqyg5lg5CdIMnQmJMjLl.png"
        },
        {
            id: 2,
            title: "Die Simpsons",
            image: "https://www.themoviedb.org/t/p/original/hpU2cHC9tk90hswCFEpf5AtbqoL.jpg",
            logo: "https://www.themoviedb.org/t/p/original/gnSUiy4K8xJqvVI8aQsIj5eH1Xj.png"
        },
        {
            id: 3,
            title: "Scrubs",
            image: "https://www.themoviedb.org/t/p/original/nWxgVgQubzlSmbjm7fbMIEeFTY4.jpg",
            logo: "https://www.themoviedb.org/t/p/original/6mCtLEhBb6dej5UOsFeUMjftOob.png"
        },
        {
            id: 4,
            title: "Brooklyn Nine-Nine",
            image: "https://www.themoviedb.org/t/p/original/9AeiA1XtP5sel2tAf9LaGeUjhDb.jpg",
            logo: "https://www.themoviedb.org/t/p/original/c4B02LhSKL6xLrI8vJ5IbLHL0Ue.png"
        },
        {
            id: 5,
            title: "Akte X - Die unheimlichen Fälle des FBI",
            image: "https://www.themoviedb.org/t/p/original/mgvZU9Q05yKmQP0Q6V05hkqnS3B.jpg",
            logo: "https://www.themoviedb.org/t/p/original/vuy45K4USzIOumeRyyFk9DDJocG.png"
        },
        {
            id: 6,
            title: "Love, Death & Robots",
            image: "https://www.themoviedb.org/t/p/original/hkkR14vBgGV4TM0e7BGlMcAQETS.jpg",
            logo: "https://www.themoviedb.org/t/p/original/5uaTEjpR8RauUq8jfh4nnz3ygru.png"
        },
        {
            id: 7,
            title: "Raumschiff Enterprise",
            image: "https://www.themoviedb.org/t/p/original/6BaBTVzNWObStYawcz6Qjkvxm2B.jpg",
            logo: "https://www.themoviedb.org/t/p/original/fRIpzKt10AeDe2tjiMi9n65qWaZ.png"
        },
        {
            id: 8,
            title: "Bob's Burgers",
            image: "https://www.themoviedb.org/t/p/original/rUABoTPO0OLq2wlHiFWezxpV6fo.jpg",
            logo: "https://www.themoviedb.org/t/p/original/vpZPfGCuyPcUompVuysb3lUmmC2.svg"
        },
        {
            id: 9,
            title: "Arrested Development",
            image: "https://www.themoviedb.org/t/p/original/ArZwmJl1y6qlnLjuE9FXlEd8RU0.jpg",
            logo: "https://www.themoviedb.org/t/p/original/ddWlOQ7kojFlp0cchDZZUNAQhMp.png"
        },
        {
            id: 10,
            title: "Resident Evil: Infinite Darkness",
            image: "https://www.themoviedb.org/t/p/original/uPHXbrh9jlq2XgfjjTFlkJfgtOQ.jpg",
            logo: "https://www.themoviedb.org/t/p/original/hOUYVW9FRyHApnONfOTYX8D935U.png"
        }
    ];
  
    // Pass data to the page via props
    return { props: { media } }
}
